clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: code-review

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment: &web-environment
      - DOCUMENT_ROOT=/test/code-review
      - COMPOSERVER=--2

pipeline:
  composer-install-lowest:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment:
      - COMPOSERVER="--2"
    volumes:
      - /cache:/cache
    commands:
      - printenv | grep COMPOSER
      -  for i; do echo $i; done
      - composer -vvv about
      - composer update --prefer-lowest --ansi
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  composer-install-highest:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache:/cache
    environment: *web-environment
    commands:
      - composer -vvv about
      - composer install --ansi
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/phpunit

matrix:
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  PHP_VERSION:
    - 7.3
    - 7.4
