workspace:
  base: /test
  path: code-review

services:
  web:
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
    environment:
      - DOCUMENT_ROOT=/test/code-review

pipeline:
  composer-install:
    group: prepare
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
    volumes:
      - /cache:/cache
    commands:
      - composer update ${COMPOSER_BOUNDARY}

  grumphp:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
    commands:
      - ./vendor/bin/phpunit

matrix:
  COMPOSER_BOUNDARY:
    - '--prefer-lowest'
    - ''
