workspace:
  base: /test
  path: code-review

services:
  web:
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    environment:
      - DOCUMENT_ROOT=/test/code-review

pipeline:
  composer-install-lowest:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    volumes:
      - /cache:/cache
    commands:
      - composer update --prefer-lowest --ansi
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  composer-install-highest:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  grumphp:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.2}
    commands:
      - ./vendor/bin/phpunit

matrix:
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  PHP_VERSION:
    - 7.1
    - 7.2
    - 7.3
