parameters:
    rules:
        '@PSR2': true
        '@PhpCsFixer': true
        '@PhpCsFixer:risky': true
        class_definition:
            multi_line_extends_each_single_line: true
        multiline_whitespace_before_semicolons:
            strategy: no_multi_line
        no_extra_blank_lines:
            tokens:
                - extra
                - curly_brace_block
                - parenthesis_brace_block
                - square_brace_block
                - return
                - throw
                - use
                - use_trait
        # Disable php_unit_strict as it might break too much things for now. Remove the line to enable it.
        php_unit_strict: false
